//------------------------------------------------------------------------
// Copyright(c) 2024 stimmer02.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"CuPressor.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"CuPressor VST3 (64Bit)"
#else
#define stringFileDescription	"CuPressor VST3"
#endif
#define stringCompanyName		"stimmer02\0"
#define stringLegalCopyright	"Copyright(c) 2024 stimmer02."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
